export const HOME_ROUTE = '/home'
export const PUBLIC_LEDGER_ROUTE = '/public-ledger'
export const FAIR_PRICE_SHOPS_ROUTE = '/fair-price-shops'
export const ALLOCATIONS_ROUTE = '/allocations'
export const TRANSPARENCY_REPORTS_ROUTE = '/transparency-reports'
export const SIGN_IN_ROUTE = '/signin'
export const OTP_VERIFICATION_ROUTE = '/otp-verification'
export const REGISTER_ROUTE = '/register'

export const DASHBOARD_OVERVIEW_ROUTE = '/dashboard/overview'
export const DASHBOARD_ALLOCATIONS_ROUTE = '/dashboard/allocations'
export const DASHBOARD_HISTORY_ROUTE = '/dashboard/history'
export const DASHBOARD_GRIEVANCES_ROUTE = '/dashboard/grievances'
export const DASHBOARD_PROFILE_ROUTE = '/dashboard/profile'
export const DASHBOARD_SETTINGS_ROUTE = '/dashboard/settings'
